### ISSUE TITLE
报错提示 cloud.init()

### ISSUE THREAD

**Issue by demostars** [guren-cloud/v-request#6]
你好，使用中有这样的提示，请教如何处理，在每个 wx.vrequest 之前加 cloud.init() ?还是？

remote-helper.js:44 [process] unhandledRejection Error: errCode: -1  | errMsg: Cloud API isn't enabled, please call wx.cloud.init first
请先调用 wx.cloud.init() 完成初始化后再调用其他云 API。init 方法可传入一个对象用于设置默认配置，详见文档。
    at new e ([publib]:1:220760)
    at Object.exportAPI.(anonymous function) [as callFunction] ([publib]:1:131763)
    at weapp:///v-request.js:61:14
    at new Promise (<anonymous>)
    at Object.wx.vrequest (weapp:///v-request.js:60:10)

**Comment by safe-dog** [comment]
请参考小程序云开发文档：
https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/getting-started.html

我们需要先开通云开发环境，然后在app.js中初始化云开发配置
